version: 1
disable_existing_loggers: false
root:
  handlers:
  - console
  - file
formatters:
  default:
    format: '%(asctime)s | %(levelname)-8s | %(name)-30s: %(message)s'
handlers:
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: default
  file:
    level: DEBUG
    class : logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/app.log
    maxBytes: 1048576
    backupCount: 10
